export type UserRole = 'user' | 'moderator' | 'admin';
export type LanguageCode = 'en' | 'uk' | 'ru';
export type OrderStatus = 'pending' | 'in_review' | 'completed' | 'rejected' | 'refunded';
export type FormType = 'i765' | 'i131' | 'i134a' | 'i90' | 'n400' | 'other';
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type ModerationStatus = 'pending' | 'approved' | 'rejected' | 'escalated';
export type SourceType = 'uscis_gov' | 'dhs_gov' | 'state_gov' | 'federal_register' | 'other_official';
export type BotPlatform = 'telegram' | 'whatsapp' | 'facebook';
export type LeadStatus = 'new' | 'contacted' | 'qualified' | 'converted' | 'spam';
