#!/usr/bin/env node
/**
 * check-no-pii.mjs — fail the build if the owner's real PII reappears in COMMITTED files.
 *
 * Why: committed code/tests/golden-vectors/docs must use FICTIONAL data only. A real
 * value hard-coded into a test proves memorization, not recognition — and leaks PII.
 * Real data lives ONLY under gitignored qa-private/ + test-fixtures/real-docs/.
 *
 * How: walks tracked text files (git ls-files), tokenizes each into Unicode word/number
 * runs, normalizes (NFC + lowercase + apostrophe-fold), SHA-256s each token, and fails on
 * any match against scripts/pii-denylist.sha256.json. The denylist stores HASHES ONLY
 * (generated by the gitignored qa-private/tools/gen-pii-denylist.mjs) so this guard never
 * itself stores a plaintext real token. Scope = surname forms + distinctive document
 * numbers; common given names and dual-use public place names are deliberately NOT listed.
 *
 *   node scripts/check-no-pii.mjs              # scan; exit 1 on any hit (CI gate)
 *   node scripts/check-no-pii.mjs --self-test  # prove the detector fires (positive+negative)
 *
 * Also importable (no side effects on import): { norm, tokenize, hashToken, scanText,
 * loadDenylist, scanRepo, selfTest } — used by the vitest wrapper so `pnpm test` enforces it.
 */
import { createHash } from 'node:crypto'
import { readFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { execSync } from 'node:child_process'

export const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..')

// Normalization — MUST stay identical to qa-private/tools/gen-pii-denylist.mjs (verified by selfTest).
export const norm = (s) => s.normalize('NFC').toLowerCase().replace(/[’ʼ`']/g, "'")
export const hashToken = (s) => createHash('sha256').update(norm(s)).digest('hex')

// Unicode word/number runs: a letter-led word (apostrophes/marks allowed) OR a 4+ digit number.
const TOKEN = /\p{L}[\p{L}\p{M}’ʼ`'-]*|\d{4,}/gu
// Strip LEADING/TRAILING quote/apostrophe/hyphen so a denylisted token wrapped in a
// string literal (e.g. quoted 'Surname') still matches; INTERNAL apostrophes (O'Brien) are kept.
export const tokenize = (text) =>
  [...text.matchAll(TOKEN)].map((m) => m[0].replace(/^[’ʼ`'\-]+|[’ʼ`'\-]+$/gu, '')).filter(Boolean)

// Scan tracked text files only (the threat model is the committed tree).
const EXT = /\.(ts|tsx|js|mjs|cjs|json|md|mdx|ya?ml|csv|sh|txt)$/i
const EXCLUDE = /^(node_modules\/|\.next\/|qa-private\/|test-fixtures\/real-docs\/|.*\.lock$|pnpm-lock\.yaml$|scripts\/pii-denylist\.sha256\.json$)/

export function loadDenylist(repo = REPO) {
  const p = resolve(repo, 'scripts/pii-denylist.sha256.json')
  if (!existsSync(p)) throw new Error(`missing denylist: ${p}`)
  return new Map(JSON.parse(readFileSync(p, 'utf8')).tokens.map((t) => [t.hash, t.hint]))
}

/** Scan a single text blob against a hash→hint map. Returns [{line, hint}]. Pure. */
export function scanText(text, hashes) {
  const out = []
  const lines = text.split('\n')
  for (let i = 0; i < lines.length; i++) {
    for (const tok of tokenize(lines[i])) {
      const hint = hashes.get(hashToken(tok))
      if (hint) out.push({ line: i + 1, hint })
    }
  }
  return out
}

/** Scan the whole tracked tree. Returns { files, hits:[{file,line,hint}] }. */
export function scanRepo(repo = REPO, hashes = loadDenylist(repo)) {
  const tracked = execSync('git ls-files', { cwd: repo, encoding: 'utf8' }).split('\n').filter(Boolean)
  const files = tracked.filter((f) => EXT.test(f) && !EXCLUDE.test(f))
  const hits = []
  for (const rel of files) {
    let text
    try { text = readFileSync(resolve(repo, rel), 'utf8') } catch { continue }
    for (const h of scanText(text, hashes)) hits.push({ file: rel, ...h })
  }
  return { files: files.length, hits }
}

/**
 * Prove the detector actually fires — WITHOUT storing any real token. Builds a throwaway
 * denylist from a SYNTHETIC token, then asserts (positive) a blob containing it is flagged
 * and (negative) clean text is not. A guard that cannot detect is worse than no guard.
 * Returns { ok, detail }.
 */
export function selfTest() {
  const SYN = 'zzsynthetic’piimarkerzz' // synthetic; contains a typographic apostrophe to also exercise norm()
  const synHashes = new Map([[hashToken(SYN), 'synthetic']])
  const positive = scanText(`a line with ${SYN} in it`, synHashes)
  const negative = scanText('completely clean text with Soloviak Andrii 530174', synHashes)
  // Normalization parity (SYNTHETIC tokens only — never a real value): a typographic
  // apostrophe must hash identically to a straight one, so apostrophe-variant PII can't slip past.
  const parity = hashToken('demo’tok') === hashToken("demo'tok")
  const ok = positive.length === 1 && negative.length === 0 && parity
  return { ok, detail: { positive: positive.length, negative: negative.length, normParity: parity } }
}

// ── CLI (only when run directly; importing has no side effects) ───────────────
const isMain = process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url
if (isMain) {
  if (process.argv.includes('--self-test')) {
    const r = selfTest()
    if (!r.ok) { console.error(`✗ PII GUARD self-test FAILED`, r.detail); process.exit(1) }
    console.log(`✓ PII GUARD self-test OK (positive+negative+norm-parity).`)
    process.exit(0)
  }
  let res
  try { res = scanRepo() } catch (e) { console.error(`FATAL: ${(e && e.message) || e}`); process.exit(2) }
  if (res.hits.length) {
    console.error(`✗ PII GUARD: ${res.hits.length} real-PII token(s) found in committed files (value redacted; hint = category):\n`)
    for (const h of res.hits) console.error(`  ${h.file}:${h.line}  [${h.hint}]`)
    console.error(`\nReplace with FICTIONAL data. Real data belongs ONLY under gitignored qa-private/.`)
    process.exit(1)
  }
  console.log(`✓ PII GUARD: clean — scanned ${res.files} tracked files, 0 real-PII tokens.`)
}
