/**
 * engine/docTypes.ts — the canonical FIELD STRUCTURE per Ukrainian document
 * type. This is the "правильная структура" the whole engine reads from:
 * which fields exist, their Ukrainian label (for HTR line→field mapping),
 * their kind (drives KMU-55 / gazetteer / date normalization), and their
 * CLASS (drives the consensus accept/confirm rule):
 *
 *   - 'open_name' : surnames, given names, free authority text. NEVER
 *                   auto-accepted even when readers agree (shared/systematic
 *                   misread guard — the "Тимофевич" case). Shown as suggestion.
 *   - 'closed'    : verifiable against a closed set / format (dates, oblast,
 *                   sex, gazetteer city, generated patronymic). Auto-accept on
 *                   agreement.
 *   - 'printed'   : machine-printed identifiers (series/number). A single
 *                   confident read is acceptable (with confirm).
 */

export type FieldKind = 'name' | 'date' | 'place_city' | 'place_oblast' | 'number' | 'sex' | 'text'
export type FieldClass = 'open_name' | 'closed' | 'printed'

export interface DocFieldSpec {
  key: string
  label_uk: string[]   // labels as they appear on the document (for HTR mapping)
  kind: FieldKind
  cls: FieldClass
  handwritten: boolean
}

export interface DocTypeSpec {
  id: string
  title_en: string
  fields: DocFieldSpec[]
}

const N = (key: string, label_uk: string[], cls: FieldClass, handwritten = true): DocFieldSpec => ({ key, label_uk, kind: 'name', cls, handwritten })
const D = (key: string, label_uk: string[], handwritten = true): DocFieldSpec => ({ key, label_uk, kind: 'date', cls: 'closed', handwritten })
const NUM = (key: string, label_uk: string[], printed = true): DocFieldSpec => ({ key, label_uk, kind: 'number', cls: printed ? 'printed' : 'closed', handwritten: !printed })

export const DOC_TYPES: Record<string, DocTypeSpec> = {
  ua_internal_passport_booklet: {
    id: 'ua_internal_passport_booklet',
    title_en: 'Ukrainian Internal Passport (Booklet)',
    fields: [
      N('family_name', ['Прізвище'], 'open_name'),
      N('given_name', ["Ім'я", 'Имя'], 'open_name'),
      N('patronymic', ['По батькові', 'Отчество'], 'closed'), // closed: validated/generated by patronymic engine
      D('dob', ['Дата народження', 'Дата рождения']),
      { key: 'sex', label_uk: ['Стать', 'Пол'], kind: 'sex', cls: 'closed', handwritten: true },
      { key: 'city_of_birth', label_uk: ['Місце народження', 'Место рождения'], kind: 'place_city', cls: 'closed', handwritten: true },
      { key: 'oblast_of_birth', label_uk: ['область', 'обл'], kind: 'place_oblast', cls: 'closed', handwritten: true },
      NUM('series_number', ['Серія', 'Серия', '№']),
    ],
  },

  ua_birth_certificate: {
    id: 'ua_birth_certificate',
    title_en: 'Ukrainian Birth Certificate',
    fields: [
      N('child_full_name', ['Громадянин', 'Гражданин', 'Прізвище'], 'open_name'),
      D('date_of_birth', ['народився', 'народилася', 'родился', 'родилась', 'Дата народження']),
      { key: 'place_of_birth', label_uk: ['Місце народження', 'Место рождения'], kind: 'place_city', cls: 'closed', handwritten: true },
      { key: 'oblast_of_birth', label_uk: ['область', 'обл'], kind: 'place_oblast', cls: 'closed', handwritten: true },
      N('father_full_name', ['Батько', 'Отец'], 'open_name'),
      N('mother_full_name', ['Мати', 'Мать'], 'open_name'),
      { key: 'place_of_registration', label_uk: ['Місце реєстрації', 'Место регистрации'], kind: 'text', cls: 'open_name', handwritten: true },
      D('date_of_issue', ['Дата видачі', 'Дата выдачи']),
      NUM('act_record_number', ['актовий запис', 'запис за №', 'запись', '№'], false),
      NUM('series_number', ['Серія', 'Серия']),
    ],
  },

  ua_marriage_certificate: {
    id: 'ua_marriage_certificate',
    title_en: 'Ukrainian Marriage Certificate',
    fields: [
      N('husband_full_name', ['чоловік', 'Прізвище'], 'open_name'),
      N('wife_full_name', ['дружина', 'Прізвище'], 'open_name'),
      D('date_of_marriage', ['зареєстрували шлюб', 'дата реєстрації шлюбу']),
      { key: 'husband_surname_after', label_uk: ['чоловіка', 'йому'], kind: 'name', cls: 'open_name', handwritten: true },
      { key: 'wife_surname_after', label_uk: ['дружини', 'їй'], kind: 'name', cls: 'open_name', handwritten: true },
      { key: 'place_of_registration', label_uk: ['Місце реєстрації', 'орган'], kind: 'text', cls: 'open_name', handwritten: true },
      NUM('act_record_number', ['актовий запис', '№'], false),
      NUM('series_number', ['Серія', '№']),
    ],
  },

  ua_divorce_certificate: {
    id: 'ua_divorce_certificate',
    title_en: 'Ukrainian Certificate of Dissolution of Marriage',
    fields: [
      N('husband_full_name', ['чоловіком', 'Прізвище'], 'open_name'),
      N('wife_full_name', ['дружиною', 'Прізвище'], 'open_name'),
      D('date_of_dissolution', ['розірвано', 'числа', 'місяця']),
      { key: 'husband_surname_after', label_uk: ['йому'], kind: 'name', cls: 'open_name', handwritten: true },
      { key: 'wife_surname_after', label_uk: ['їй'], kind: 'name', cls: 'open_name', handwritten: true },
      { key: 'place_of_registration', label_uk: ['Місце державної реєстрації', 'орган'], kind: 'text', cls: 'open_name', handwritten: true },
      NUM('act_record_number', ['актовий запис', '№'], false),
      NUM('series_number', ['Серія', '№']),
    ],
  },

  ua_military_id: {
    id: 'ua_military_id',
    title_en: 'Ukrainian Military Service Record',
    fields: [
      N('family_name', ['Прізвище'], 'open_name'),
      N('given_name', ["Ім'я"], 'open_name'),
      N('patronymic', ['По батькові'], 'closed'),
      D('date_of_birth', ['Дата народження', 'народження']),
      { key: 'place_of_birth', label_uk: ['Місце народження'], kind: 'place_city', cls: 'closed', handwritten: true },
      NUM('series_number', ['Серія', '№']),
    ],
  },
}

/** Convenience selectors used by the orchestrator. */
export function printedFields(spec: DocTypeSpec): string[] {
  return spec.fields.filter((f) => f.cls === 'printed').map((f) => f.key)
}
export function openNameFields(spec: DocTypeSpec): string[] {
  return spec.fields.filter((f) => f.cls === 'open_name').map((f) => f.key)
}
